const parameterRegexMap = {
    "WBC": /WBC\|(\d+\.\d+)\s*!/,
    "RBC": /RBC\|(\d+\.\d+)\s*!/,
    "HGB": /HGB\|(\d+\.\d+)\s*!/,
    "HCT": /HCT\|(\d+\.\d+)\s*!/,
    "MCV": /MCV\|(\d+\.\d+)\s*!/,
    "MCH": /MCH\|(\d+\.\d+)\s*!/,
    "MCHC": /MCHC\|(\d+\.\d+)\s*!/,
    "PLT": /PLT\|(\d+\.\d+)\s*!/,
    "LYMPH%": /LY%\|(\d+\.\d+)\s*!/,
    "MONO%": /MO%\|(\d+\.\d+)\s*!/,
    "NEUT%": /NE%\|(\d+\.\d+)\s*!/,
    "EO%": /EO%\|(\d+\.\d+)\s*!/,
    "BASO%": /BA%\|(\d+\.\d+)\s*!/,
    "LYMPH#": /LY#\|(\d+\.\d+)\s*!/,
    "MONO#": /MO#\|(\d+\.\d+)\s*!/,
    "NEUT#": /NE#\|(\d+\.\d+)\s*!/,
    "EO#": /EO#\|(\d+\.\d+)\s*!/,
    "BASO#": /BA\|(\d+\.\d+)\s*\s*!/,
    "RDW-CV": /RDW-CV\|(\d+\.\d+)\s*!/,
    "RDW-SD": /RDW-SD\|(\d+\.\d+)\s*!/,
    "PDW": /PDW\|(\d+\.\d+)\s*!/,
    "MPV": /MPV\|(\d+\.\d+)\s*!/,
    "P-LCR": /P-LCR\|(\d+\.\d+)\s*!/,
    "RET%": /RET%\|(\d+\.\d+)\s*!/,
    "RET#": /RET#\|(\d+\.\d+)\s*!/,
    "IRF": /IRF\|(\d+\.\d+)\s*!/,
    "LFR": /LFR\|(\d+\.\d+)\s*!/,
    "MFR": /MFR\|(\d+\.\d+)\s*!/,
    "HFR": /HFR\|(\d+\.\d+)\s*!/,
    "PCT": /PCT%\|(\d+\.\d+)\s*!/,
    "NRBC%": /NRBC%\|(\d+\.\d+)\s*!/,
    "NRBC#": /NRBC#\|(\d+\.\d+)\s*!/,
    "IG#": /IG#\|(\d+\.\d+)\s*!/,
    "IG%": /IG%\|(\d+\.\d+)\s*!/,
    "blank": /blank\|(\d+\.\d+)\s*!/,
    "RET-He": /RET-He\|(\d+\.\d+)!/
};

module.exports = { parameterRegexMap }
