var format = [
    {"WBC" : 'NaN'},
    {'RBC' : 'NaN'},
    {'HGB' : 'NaN'},
    {'HCT' : 'NaN'},
    {'MCV' : 'NaN'},
    {'MCH' : 'NaN'},
    {'MCHC' : 'NaN'},
    {'PLT' : 'NaN'},
    {'LYMPH%' : 'NaN'},
    {'MONO%' : 'NaN'},
    {'NEUT%' : 'NaN'},
    {'EO%' : 'NaN'},
    {'BASO%' : 'NaN'},
    {'LYMPH#' : 'NaN'},
    {'MONO#' : 'NaN'},
    {'NEUT#' : 'NaN'},
    {'EO#' : 'NaN'},
    {'BASO#' : 'NaN'},
    {'RDW-CV' : 'NaN'},
    {'RDW-SD' : 'NaN'},
    {'PDW' : 'NaN'},
    {'MPV' : 'NaN'},
    {'P-LCR' : 'NaN'},
    {'RET%' : 'NaN'},
    {'RET#' : 'NaN'},
    {'IRF' : 'NaN'},
    {'LFR' : 'NaN'},
    {'MFR' : 'NaN'},
    {'HFR' : 'NaN'},
    {'PCT' : 'NaN'},
    {'NRBC%' : 'NaN'},
    {'NRBC#' : 'NaN'},
    {'IG#' : 'NaN'},
    {'IG%' : 'NaN'},
    {'blank' : 'NaN'},
    {'RET-He' : 'NaN' }
]

module.exports = { format };
