const parameterRegexMap = {
    "WBC": /\|\d+\|\^\^\^\^WBC\^1\|\s*([\d.]+)\|g\/dL\|/,
    "RBC": /\|\d+\|\^\^\^\^RBC\^1\|\s*([\d.]+)\|g\/dL\|/,
    "HGB": /\|\d+\|\^\^\^\^HGB\^1\|\s*([\d.]+)\|g\/dL\|/,
    "HCT":  /\^\^\^\^HCT\\([^\^]+)/,
    "MCV": /MCV\|([\d.]+) /,
    "MCH": /MCH\|([\d.]+) /,
    "MCHC": /MCHC\|([\d.]+) /,
    "PLT": /PLT\|([\d.]+) /,
    "LYMPH%": /LY%\|([\d.]+) /,
    "MONO%": /MO%\|([\d.]+) /,
    "NEUT%": /NE%\|([\d.]+) /,
    "EO%": /EO%\|([\d.]+) /,
    "BASO%": /BA%\|([\d.]+) /,
    "LYMPH#": /LY#\|([\d.]+) /,
    "MONO#": /MO#\|([\d.]+) /,
    "NEUT#": /NE#\|([\d.]+) /,
    "EO#": /EO#\|([\d.]+) /,
    "BASO#": /BA#\|([\d.]+) /,
    "RDW-CV": /RDW-CV\|([\d.]+) /,
    "RDW-SD": /RSW-SD\|([\d.]+) /,
    "PDW": /PDW\|([\d.]+) /,
    "MPV": /MP\|([\d.]+) /,
    "P-LCR": /P-LCR\|([\d.]+) /,
    "RET%": /RET%\|([\d.]+) /,
    "RET#": /RET#\|([\d.]+) /,
    "IRF": /IRF\|([\d.]+) /,
    "LFR": /LFR\|([\d.]+) /,
    "MFR": /MFR\|([\d.]+) /,
    "HFR": /HFR\|([\d.]+) /,
    "PCT": /\^\^\^\^PCT\^1\|\s*([\d.]+)\|%|/,
    "NRBC%": /NRBC%\|([\d.]+) /,
    "NRBC#": /NRBC#\|([\d.]+) /,
    "IG#": /IG#\|([\d.]+) /,
    "IG%": /IG%\|([\d.]+) /,
    "blank": /blank\|([\d.]+) /,
    "RET-He": /RET-He\|([\d.]+) /
};

module.exports = { parameterRegexMap }
